#include "config.h"
#include "MWatch.h"

#ifndef LVGL_DECLARE
#define LVGL_DECLARE

#define LV_COLOR_DARKGRAY LV_COLOR_MAKE(169, 169, 169)

LV_IMG_DECLARE(NUM_0_IMG);
LV_IMG_DECLARE(NUM_1_IMG);
LV_IMG_DECLARE(NUM_2_IMG);
LV_IMG_DECLARE(NUM_3_IMG);
LV_IMG_DECLARE(NUM_4_IMG);
LV_IMG_DECLARE(NUM_5_IMG);
LV_IMG_DECLARE(NUM_6_IMG);
LV_IMG_DECLARE(NUM_7_IMG);
LV_IMG_DECLARE(NUM_8_IMG);
LV_IMG_DECLARE(NUM_9_IMG);
LV_IMG_DECLARE(POINTS_IMG);

#endif